services:
  mosquitto:
    build: ./mqtt-broker
    container_name: mqtt-broker
    restart: unless-stopped
    ports:
      - "8883:8883"  # MQTT port
      - "9001:9001"  # WebSocket port
    volumes:
      # - ./mqtt-broker/certs:/mosquitto/certs # For TLS
      - ./mqtt-broker/config:/mosquitto/config
      - ./mqtt-broker/log:/mosquitto/log
      - /mosquitto/data
    environment:
      - TZ=UTC
  app:
    build: ./app
    container_name: app-backend
    ports:
      - 8000:8000
    environment:
      - MQTT_BROKER=192.168.1.76
  scooter:
    build: ./scooter
    container_name: scooter-420
  frontend:
    build: ./frontend
    container_name: app-frontend
    network_mode: host